package ac.diu.asad.conference.model;
// Generated Feb 19, 2020 12:53:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
//import org.springframework.data.annotation.Id;
import javax.persistence.Id;

/**
 * Facilities generated by hbm2java
 */
@Entity
public class Facilities  implements java.io.Serializable {

	 @Id
	 @GeneratedValue(strategy=GenerationType.AUTO)
     private int facilitiesId;
     private String facilitiesName;
     private Date facilitiesDate;

    public Facilities() {
    }

    public Facilities(int facilitiesId, String facilitiesName, Date facilitiesDate) {
       this.facilitiesId = facilitiesId;
       this.facilitiesName = facilitiesName;
       this.facilitiesDate = facilitiesDate;
    }
   
    public int getFacilitiesId() {
        return this.facilitiesId;
    }
    
    public void setFacilitiesId(int facilitiesId) {
        this.facilitiesId = facilitiesId;
    }
    public String getFacilitiesName() {
        return this.facilitiesName;
    }
    
    public void setFacilitiesName(String facilitiesName) {
        this.facilitiesName = facilitiesName;
    }
    public Date getFacilitiesDate() {
        return this.facilitiesDate;
    }
    
    public void setFacilitiesDate(Date facilitiesDate) {
        this.facilitiesDate = facilitiesDate;
    }




}


