package ac.diu.asad.conference.model;
// Generated Feb 19, 2020 12:53:09 PM by Hibernate Tools 4.3.1



/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private int roomNumber;
     private int roomCapcity;
     private String width;
     private String height;

    public Room() {
    }

    public Room(int roomNumber, int roomCapcity, String width, String height) {
       this.roomNumber = roomNumber;
       this.roomCapcity = roomCapcity;
       this.width = width;
       this.height = height;
    }
   
    public int getRoomNumber() {
        return this.roomNumber;
    }
    
    public void setRoomNumber(int roomNumber) {
        this.roomNumber = roomNumber;
    }
    public int getRoomCapcity() {
        return this.roomCapcity;
    }
    
    public void setRoomCapcity(int roomCapcity) {
        this.roomCapcity = roomCapcity;
    }
    public String getWidth() {
        return this.width;
    }
    
    public void setWidth(String width) {
        this.width = width;
    }
    public String getHeight() {
        return this.height;
    }
    
    public void setHeight(String height) {
        this.height = height;
    }

   




}


