package ac.diu.asad.conference.model;
// Generated Feb 19, 2020 12:53:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Speaker generated by hbm2java
 */
@Entity
public class Speaker  implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
     private int speakerId;
     private String speakerName;

    public Speaker() {
    }

    public Speaker(int speakerId, String speakerName) {
       this.speakerId = speakerId;
       this.speakerName = speakerName;
    }
   
    public int getSpeakerId() {
        return this.speakerId;
    }
    
    public void setSpeakerId(int speakerId) {
        this.speakerId = speakerId;
    }
    public String getSpeakerName() {
        return this.speakerName;
    }
    
    public void setSpeakerName(String speakerName) {
        this.speakerName = speakerName;
    }




}


