package ac.diu.asad.conference.model;
// Generated Feb 19, 2020 12:53:09 PM by Hibernate Tools 4.3.1



/**
 * Topics generated by hbm2java
 */
public class Topics  implements java.io.Serializable {


     private int topicsId;
     private String topicsName;

    public Topics() {
    }

    public Topics(int topicsId, String topicsName) {
       this.topicsId = topicsId;
       this.topicsName = topicsName;
    }
   
    public int getTopicsId() {
        return this.topicsId;
    }
    
    public void setTopicsId(int topicsId) {
        this.topicsId = topicsId;
    }
    public String getTopicsName() {
        return this.topicsName;
    }
    
    public void setTopicsName(String topicsName) {
        this.topicsName = topicsName;
    }




}


