package ac.diu.asad.conference.model;
// Generated Feb 19, 2020 12:53:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * University generated by hbm2java
 */
@Entity
public class University  implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
     private int universityId;
     private String universityName;
     private float universityRating;
     private String universityAdress;

    public University() {
    }

    public University(int universityId, String universityName, float universityRating, String universityAdress) {
       this.universityId = universityId;
       this.universityName = universityName;
       this.universityRating = universityRating;
       this.universityAdress = universityAdress;
    }
   
    public int getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(int universityId) {
        this.universityId = universityId;
    }
    public String getUniversityName() {
        return this.universityName;
    }
    
    public void setUniversityName(String universityName) {
        this.universityName = universityName;
    }
    public float getUniversityRating() {
        return this.universityRating;
    }
    
    public void setUniversityRating(float universityRating) {
        this.universityRating = universityRating;
    }
    public String getUniversityAdress() {
        return this.universityAdress;
    }
    
    public void setUniversityAdress(String universityAdress) {
        this.universityAdress = universityAdress;
    }




}


